import Sidebar from "@/components/Sidebar/Sidebar";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <div className="relative flex p-4 h-screen overflow-hidden">
          <Sidebar />
          <main className="pl-24 pr-5 pt-[72px] w-full overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
